### ISSUE TITLE
Warnings when a request starts a new process

### ISSUE THREAD

**Issue by Burtan** [cloudendpoints/endpoints-java#56]
Hi, 
when my automatically scaled appengine is woken up by a request, I always get the following warnings since using Endpoints V2. 

```
com.google.api.control.Client start: no scheduler thread, schedule.run will be invoked by report(...) (Client.java:126)
java.lang.IllegalStateException: This feature is only available to backend instances.
	at com.google.appengine.api.system.SystemServiceImpl.translateException(SystemServiceImpl.java:40)
	at com.google.appengine.api.system.SystemServiceImpl.startBackgroundRequest(SystemServiceImpl.java:28)
	at com.google.apphosting.runtime.ApiProxyImpl$BackgroundThreadFactory.newThread(ApiProxyImpl.java:1280)
	at com.google.api.control.Client.start(Client.java:118)
	at com.google.api.control.ControlFilter.init(ControlFilter.java:135)
	at org.mortbay.jetty.servlet.FilterHolder.doStart(FilterHolder.java:97)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:662)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.createHandler(AppVersionHandlerMap.java:203)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.getHandler(AppVersionHandlerMap.java:176)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:133)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:559)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:519)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:489)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:293)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:238)
	at java.lang.Thread.run(Thread.java:745)
```
```
com.google.api.client.googleapis.services.AbstractGoogleClient <init>: Application name is not set. Call Builder#setApplicationName. 
```

**Comment by tangiel** [comment]
This is somewhat intentional, because when you use the management libraries with App Engine Standard, there is no way to flush metric reporting requests in the background, so they are batched after certain requests. Therefore, you may not see metrics appear until after enough requests take place.

**Comment by william-ferguson-au** [comment]
But logging this at warning with `java.lang.IllegalStateException: This feature is only available to backend instances.` ??

We're not doing anything wrong with our apps. This is an IllegalState that is being generated by AppEngine itself when it starts a new instance. If this IllegalState is not relevant then AppENgine should be dealing with it instead of reporting it to the application.

NB I always see the above error paired with `com.google.api.client.googleapis.services.AbstractGoogleClient <init>: Application name is not set. Call Builder#setApplicationName. (AbstractGoogleClient.java:81)`. Which I presume is also called by the AppEngine mechanics.

Can we get these cleaned up please?

**Comment by tangiel** [comment]
The reason why the first message is logged is because users with very low QPS (below 1) will not currently get traffic reported in a timely manner, because data is flushed periodically. When you run a frontend instance, there are no background threads, so data is flushed every so many requests. I agree that it's a lot scarier than it looks, but I don't think we should completely get rid of it. I'm thinking to remove the exception logging and making it a more clear explanation.

**Comment by tangiel** [comment]
Both logging instances should be fixed in https://github.com/cloudendpoints/endpoints-management-java/pull/26.
